server:
  port: 9090

spring:
  application:
    name: api-gateway11

  cloud:
    gateway:
      routes:

        - id: doctor-service-route
          uri: lb://DOCTOR-SERVICE11
          predicates:
            - Path=/doctor/**

        - id: appointment-service-route
          uri: lb://APPOINTMENT-SERVICE11
          predicates:
            - Path=/appointments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
